name: Compliance Assessment

on:
  push:
    branches:
      - 13.11.2024
  pull_request:

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run compliance checks
        run: |
          python scripts/compliance_check.py

      - name: Upload compliance report
        uses: actions/upload-artifact@v2
        with:
          name: compliance-report
          path: reports/compliance_report.pdf

  notify:
    runs-on: ubuntu-latest
    needs: compliance-check
    steps:
      - name: Notify team
        run: |
          echo "Compliance assessment completed. Check the report in the artifacts."
