name: Neuro_pipeline

on:
  push:
    branches:
      - 13.11.2024

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
